<a href="https://colab.research.google.com/github/pathanzaheer/machine-learning-/blob/main/Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Perform arithmetic operations on NumPy arrays.

In [1]:
# importing numpy module
import numpy as np

# creating array using numpy
a = np.array([1,2,3]) # array 01

# opertions on numpy array
print("Addition:", a+5) # adding 5 to array
print("Subration:", 5-a) # subtracting array from 5
print("Multiplication:", a*5) # multiplying 5 with array
print("Division:", 5/a) # dividing 5 with array

Addition: [6 7 8]
Subration: [4 3 2]
Multiplication: [ 5 10 15]
Division: [5.         2.5        1.66666667]


2.Write a script to compute the mean and standard deviation of a NumPy array.

In [2]:
# mean
mean = np.mean(a)
print(mean)

# standard deviation
sd = np.std(a)
print(sd)

2.0
0.816496580927726


3.Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [3]:
# creating array
arr = np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


4.Reshape the array into a 2x4 matrix.

In [4]:
rearr = np.reshape(arr,(2,4))
print(rearr)

[[10 15 20 25]
 [30 35 40 45]]


5.Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0.

In [6]:
#  creating 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# extracting last two rows and first two columns
subArr = arr[1:,:2]
print(subArr)

# replacing all elements greater than 4 with 0
arr[arr>4] = 0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


6.Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.

In [7]:
# creating array using numpy
a = np.array([1,2,3]) # array 01
b = np.array([4,5,6]) # array 02

# opertions on numpy array
print("Addition:", a+b) # addition of two numpy arrays
print("Subration:", b-a) # subtraction of two numpy arrays
print("Multiplication:", a*b) # multiplication of two numpy arrays
print("Division:", b/a) # division of two numpy arrays

Addition: [5 7 9]
Subration: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


7.Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [8]:
# creating random integer array
ramArr = np.random.rand(4,4)
print(ramArr)

# mean of each column
print(np.mean(ramArr, axis = 0))

# maximum value
print(np.max(ramArr))

# sum of all elements
print(np.sum(ramArr))

[[0.69972832 0.44073053 0.90152766 0.53081069]
 [0.19762994 0.02271823 0.54989449 0.36118747]
 [0.28838642 0.9522072  0.57130043 0.51826495]
 [0.48179108 0.3776349  0.28480592 0.66931875]]
[0.41688394 0.44832271 0.57688212 0.51989546]
0.9522071963506857
7.847936981607042


8.Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2.

In [9]:
# creating array
arr = np.array([1,2,3,4])

# adding 10 to each elements
result = arr+10

# multiplying 2 to the result
result = result*2
print(result)

[22 24 26 28]


9.Perform advanced slicing and indexing on a 3D array. Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100.
Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1.

In [10]:
#  Creating a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from 1 to 100.
arr = np.random.randint(1,100,(3,4,5))
print(arr)

[[[68  6 16  9 12]
  [40 19 92 87 72]
  [10 74 53 98 30]
  [42  7 81 41 62]]

 [[32 73 25 83 97]
  [59 47 42  3 59]
  [69  5 82 76 24]
  [51 56 32 55 39]]

 [[43 65 99 63 37]
  [78 65 51 63 72]
  [73 12 88 23 33]
  [ 1 43 95 64 80]]]


10.Work with broadcasting and advanced operations in NumPy. Create a NumPy array arr of shape (3, 3) with random integers between 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array.

In [11]:
#  Creating a NumPy array arr of shape (3, 3) with random integers between 1 and 20.
arr = np.random.randint(1,20,(3,3))
print(arr)

# squaring the array
newArr = np.square(arr)
print(newArr)

# subtracting the mean of each row from its respective elements (row-wise normalization)
arr = arr - arr.mean(axis=1, keepdims=True)

# top 3 maximum values
sortArr = np.sort(arr.flatten())
print(sortArr[-3:])

[[ 2  7 13]
 [ 6 16  5]
 [19 12  4]]
[[  4  49 169]
 [ 36 256  25]
 [361 144  16]]
[5.66666667 7.         7.33333333]
